# Generated by Django 5.2 on 2025-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
