# Generated by Django 5.2 on 2025-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_remove_ad_image_url_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Электроника"),
                    ("clothing", "Одежда и обувь"),
                    ("tech", "Техника"),
                    ("furniture", "Мебель"),
                    ("real_estate", "Недвижимость"),
                    ("auto", "Авто"),
                    ("construction", "Строительство"),
                    ("other", "Прочее"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
